index:
   path: /api/v1/
   controller: App\Controller\UserController::index
wxIn:
    path: /api/v1/wxIn
    controller: App\Controller\UserController::wxIn
checkSign:
    path: /api/v1/checkSign
    controller: App\Controller\UserController::checkSign
sign:
    path: /api/v1/sign
    controller: App\Controller\UserController::sign
signOut:
    path: /api/v1/signOut
    controller: App\Controller\UserController::signOut
score:
    path: /api/v1/score
    controller: App\Controller\ScoreController::index
lesson:
    path: /api/v1/lesson
    controller: App\Controller\LessonController::index
permit:
    path: /api/v1/getPermit
    controller: App\Controller\PermissionController::getPermit
permit-score:
    path: /api/v1/permit/score
    controller: App\Controller\PermissionController::switchScore
permit-item:
    path: /api/v1/permit/item
    controller: App\Controller\PermissionController::switchItem

page-score:
    path: /score
    controller: App\Controller\PageController::score
page-index:
    path: /
    controller: App\Controller\PageController::score
page-lesson:
    path: /lesson
    controller: App\Controller\PageController::lesson
page-sign:
    path: /sign
    controller: App\Controller\PageController::sign
page-oauth:
    path: /oauth
    controller: App\Controller\PageController::oauth
page-auto:
    path: /auto
    controller: App\Controller\PageController::auto
page-permit:
    path: /permit
    controller: App\Controller\PageController::permit

signout:
    path: /signout
    controller: App\Controller\UserController::signOut