index:
   path: /
   controller: App\Controller\UserController::index
wxIn:
    path: /wxIn
    controller: App\Controller\UserController::wxIn
sign:
    path: /api/v1/sign
    controller: App\Controller\UserController::sign
signOut:
    path: /api/v1/signOut
    controller: App\Controller\UserController::signOut
score:
    path: /api/v1/score
    controller: App\Controller\ScoreController::index
lesson:
    path: /api/v1/lesson
    controller: App\Controller\LessonController::index

page-score:
    path: /score
    controller: App\Controller\PageController::score
page-lesson:
    path: /lesson
    controller: App\Controller\PageController::lesson
page-oauth:
    path: /oauth
    controller: App\Controller\PageController::oauth